spring:
  config:
    import: env.yml
  application:
    name: account

#  datasource:
#      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://a301-rds.cz4ggd8ra6pu.ap-northeast-2.rds.amazonaws.com:3306/account
#      username: ${DB_USERNAME}
#      password: ${DB_PASSWORD}
  datasource:
    url: jdbc:h2:tcp://localhost/~/account
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: walet
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    region:
      static: ap-east-2
    stack:
      auto: false