spring:
  config:
    import: env.yml
  application:
    name: AUTH
  main:
    allow-bean-definition-overriding: true

jwt:
  secret-key: ${JWT_SECRET_KEY}

hash:
  pepper: ${PEPPER}

coolsms:
  api:
    key: "API Key"
    secret: "API Secret"
